# -*- coding: utf-8 -*-
"""modelling_tuning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACEySUUtZclOk5gHictgkAAnQdk6SZy8
"""

"""
Modelling Script with Hyperparameter Tuning & Manual Logging
Kriteria 2 - Skilled Level
"""

import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os
import json
import warnings
warnings.filterwarnings('ignore')

# Set MLflow tracking URI
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Telco_Churn_Skilled_Tuning")

def load_data():
    """Load preprocessed data"""
    train_path = "dataset_preprocessed/telco_churn_train.csv"
    test_path = "dataset_preprocessed/telco_churn_test.csv"

    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)

    X_train = train_df.drop('Churn', axis=1)
    y_train = train_df['Churn']
    X_test = test_df.drop('Churn', axis=1)
    y_test = test_df['Churn']

    print(f" Data loaded: Train={X_train.shape}, Test={X_test.shape}")
    return X_train, X_test, y_train, y_test

def plot_confusion_matrix(y_true, y_pred, model_name):
    """Plot and save confusion matrix"""
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['No Churn', 'Churn'],
                yticklabels=['No Churn', 'Churn'])
    plt.title(f'Confusion Matrix - {model_name}')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')

    # Save plot
    filename = f"confusion_matrix_{model_name.replace(' ', '_')}.png"
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()
    return filename

def plot_feature_importance(model, feature_names, model_name):
    """Plot and save feature importance (for Random Forest)"""
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_
        indices = np.argsort(importances)[-15:]  # Top 15 features

        plt.figure(figsize=(10, 8))
        plt.barh(range(len(indices)), importances[indices], color='skyblue')
        plt.yticks(range(len(indices)), [feature_names[i] for i in indices])
        plt.xlabel('Feature Importance')
        plt.title(f'Top 15 Feature Importance - {model_name}')

        filename = f"feature_importance_{model_name.replace(' ', '_')}.png"
        plt.savefig(filename, dpi=150, bbox_inches='tight')
        plt.close()
        return filename
    return None

def train_with_tuning(X_train, y_train, X_test, y_test):
    """Train models with hyperparameter tuning and manual logging"""

    feature_names = X_train.columns.tolist()

    # ========== RANDOM FOREST WITH TUNING ==========
    print("\n" + "=" * 60)
    print("🌲 RANDOM FOREST - Hyperparameter Tuning")
    print("=" * 60)

    rf_param_grid = {
        'n_estimators': [50, 100, 200],
        'max_depth': [10, 20, None],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4]
    }

    with mlflow.start_run(run_name="RandomForest_Tuned") as rf_run:
        print(f"Run ID: {rf_run.info.run_id}")

        # Grid Search
        rf_base = RandomForestClassifier(random_state=42, n_jobs=-1)
        rf_grid = GridSearchCV(rf_base, rf_param_grid, cv=5, scoring='roc_auc', n_jobs=-1, verbose=1)
        rf_grid.fit(X_train, y_train)

        best_rf = rf_grid.best_estimator_
        print(f" Best parameters: {rf_grid.best_params_}")
        print(f" Best CV score: {rf_grid.best_score_:.4f}")

        # Predictions
        y_pred_rf = best_rf.predict(X_test)
        y_pred_proba_rf = best_rf.predict_proba(X_test)[:, 1]

        # Calculate metrics
        metrics_rf = {
            "accuracy": accuracy_score(y_test, y_pred_rf),
            "precision": precision_score(y_test, y_pred_rf),
            "recall": recall_score(y_test, y_pred_rf),
            "f1_score": f1_score(y_test, y_pred_rf),
            "roc_auc": roc_auc_score(y_test, y_pred_proba_rf),
            "best_cv_score": rf_grid.best_score_
        }

        # MANUAL LOGGING - Parameters
        mlflow.log_params(rf_grid.best_params_)
        mlflow.log_param("model_type", "RandomForest")
        mlflow.log_param("cv_folds", 5)

        # MANUAL LOGGING - Metrics
        for metric_name, metric_value in metrics_rf.items():
            mlflow.log_metric(metric_name, metric_value)

        # MANUAL LOGGING - Model
        mlflow.sklearn.log_model(best_rf, "model")

        # MANUAL LOGGING - Additional Artifacts
        # 1. Confusion Matrix Plot
        cm_plot = plot_confusion_matrix(y_test, y_pred_rf, "RandomForest_Tuned")
        mlflow.log_artifact(cm_plot)

        # 2. Feature Importance Plot
        fi_plot = plot_feature_importance(best_rf, feature_names, "RandomForest_Tuned")
        if fi_plot:
            mlflow.log_artifact(fi_plot)

        # 3. Classification Report
        report = classification_report(y_test, y_pred_rf, output_dict=True)
        report_path = "classification_report_RF.json"
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=4)
        mlflow.log_artifact(report_path)

        print(f"\n Random Forest Test Metrics:")
        for metric, value in metrics_rf.items():
            print(f"   {metric}: {value:.4f}")

    # ========== LOGISTIC REGRESSION WITH TUNING ==========
    print("\n" + "=" * 60)
    print("📈 LOGISTIC REGRESSION - Hyperparameter Tuning")
    print("=" * 60)

    lr_param_grid = {
        'C': [0.01, 0.1, 1, 10],
        'penalty': ['l1', 'l2'],
        'solver': ['liblinear', 'saga'],
        'max_iter': [1000, 2000]
    }

    with mlflow.start_run(run_name="LogisticRegression_Tuned") as lr_run:
        print(f"Run ID: {lr_run.info.run_id}")

        # Grid Search
        lr_base = LogisticRegression(random_state=42)
        lr_grid = GridSearchCV(lr_base, lr_param_grid, cv=5, scoring='roc_auc', n_jobs=-1, verbose=1)
        lr_grid.fit(X_train, y_train)

        best_lr = lr_grid.best_estimator_
        print(f" Best parameters: {lr_grid.best_params_}")
        print(f" Best CV score: {lr_grid.best_score_:.4f}")

        # Predictions
        y_pred_lr = best_lr.predict(X_test)
        y_pred_proba_lr = best_lr.predict_proba(X_test)[:, 1]

        # Calculate metrics
        metrics_lr = {
            "accuracy": accuracy_score(y_test, y_pred_lr),
            "precision": precision_score(y_test, y_pred_lr),
            "recall": recall_score(y_test, y_pred_lr),
            "f1_score": f1_score(y_test, y_pred_lr),
            "roc_auc": roc_auc_score(y_test, y_pred_proba_lr),
            "best_cv_score": lr_grid.best_score_
        }

        # MANUAL LOGGING - Parameters
        mlflow.log_params(lr_grid.best_params_)
        mlflow.log_param("model_type", "LogisticRegression")
        mlflow.log_param("cv_folds", 5)

        # MANUAL LOGGING - Metrics
        for metric_name, metric_value in metrics_lr.items():
            mlflow.log_metric(metric_name, metric_value)

        # MANUAL LOGGING - Model
        mlflow.sklearn.log_model(best_lr, "model")

        # MANUAL LOGGING - Additional Artifacts
        # 1. Confusion Matrix Plot
        cm_plot = plot_confusion_matrix(y_test, y_pred_lr, "LogisticRegression_Tuned")
        mlflow.log_artifact(cm_plot)

        # 2. Coefficients Plot
        if hasattr(best_lr, 'coef_'):
            coef = best_lr.coef_[0]
            top_indices = np.argsort(np.abs(coef))[-15:]

            plt.figure(figsize=(10, 8))
            plt.barh(range(len(top_indices)), coef[top_indices], color='lightcoral')
            plt.yticks(range(len(top_indices)), [feature_names[i] for i in top_indices])
            plt.xlabel('Coefficient Value')
            plt.title('Top 15 Feature Coefficients - Logistic Regression')

            coef_plot = "coefficients_LR.png"
            plt.savefig(coef_plot, dpi=150, bbox_inches='tight')
            plt.close()
            mlflow.log_artifact(coef_plot)

        # 3. Classification Report
        report = classification_report(y_test, y_pred_lr, output_dict=True)
        report_path = "classification_report_LR.json"
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=4)
        mlflow.log_artifact(report_path)

        print(f"\n Logistic Regression Test Metrics:")
        for metric, value in metrics_lr.items():
            print(f"   {metric}: {value:.4f}")

    return best_rf, best_lr

def main():
    print("=" * 60)
    print(" MLflow Modelling - Skilled Level")
    print(" Manual Logging + Hyperparameter Tuning")
    print("=" * 60)

    # Load data
    X_train, X_test, y_train, y_test = load_data()

    # Train with tuning
    best_rf, best_lr = train_with_tuning(X_train, y_train, X_test, y_test)

    # Save best model
    os.makedirs("models", exist_ok=True)
    joblib.dump(best_rf, "models/best_rf_model.pkl")
    joblib.dump(best_lr, "models/best_lr_model.pkl")
    print("\n Best models saved to 'models/' folder")

    print("\n" + "=" * 60)
    print(" TRAINING COMPLETE!")
    print(" Check MLflow UI at: http://127.0.0.1:5000")
    print("=" * 60)

if __name__ == "__main__":
    main()