# -*- coding: utf-8 -*-
"""modelling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGThQ7pBtkSykyJuu964wrilE9JYfh_G
"""

"""
Modelling Script with MLflow Autolog
Kriteria 2 - Basic Level
"""

import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import train_test_split
import joblib
import os
import warnings
# Set MLflow tracking to local
mlflow.set_tracking_uri("file:./mlruns")
warnings.filterwarnings('ignore')

# Set MLflow tracking URI ke localhost
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Telco_Churn_Basic")

# Enable autolog
mlflow.sklearn.autolog()

def load_data():
    """Load preprocessed data"""
    train_path = "dataset_preprocessed/telco_churn_train.csv"
    test_path = "dataset_preprocessed/telco_churn_test.csv"

    train_df = pd.read_csv(train_path)
    test_df = pd.read_csv(test_path)

    X_train = train_df.drop('Churn', axis=1)
    y_train = train_df['Churn']
    X_test = test_df.drop('Churn', axis=1)
    y_test = test_df['Churn']

    print(f" Data loaded: Train={X_train.shape}, Test={X_test.shape}")
    return X_train, X_test, y_train, y_test

def train_random_forest(X_train, y_train):
    """Train Random Forest model"""
    with mlflow.start_run(run_name="RandomForest_Baseline"):
        model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
        model.fit(X_train, y_train)
        print(" Random Forest trained")
    return model

def train_logistic_regression(X_train, y_train):
    """Train Logistic Regression model"""
    with mlflow.start_run(run_name="LogisticRegression_Baseline"):
        model = LogisticRegression(max_iter=1000, random_state=42)
        model.fit(X_train, y_train)
        print(" Logistic Regression trained")
    return model

def evaluate_model(model, X_test, y_test, model_name):
    """Evaluate model and log metrics"""
    y_pred = model.predict(X_test)

    metrics = {
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1_score": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_pred)
    }

    print(f"\n {model_name} Evaluation:")
    for metric, value in metrics.items():
        print(f"   {metric}: {value:.4f}")

    return metrics

def main():
    print("=" * 60)
    print(" MLflow Modelling - Basic Level (Autolog)")
    print("=" * 60)

    # Load data
    X_train, X_test, y_train, y_test = load_data()

    # Train models
    print("\n Training Random Forest...")
    rf_model = train_random_forest(X_train, y_train)
    evaluate_model(rf_model, X_test, y_test, "Random Forest")

    print("\n Training Logistic Regression...")
    lr_model = train_logistic_regression(X_train, y_train)
    evaluate_model(lr_model, X_test, y_test, "Logistic Regression")

    print("\n" + "=" * 60)
    print(" Training Complete! Check MLflow UI at http://127.0.0.1:5000")
    print("=" * 60)

if __name__ == "__main__":
    main()